"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

type Payment = { _id: string; invoice?: { invoiceNumber: string }; freelancer?: { name: string }; project?: { name: string }; amount: number; paymentDate: string; paymentMethod: string; status: string };
export default function ClientPaymentsPage() {
  const [payments, setPayments] = useState<Payment[]>([]);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("All");
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/payments").then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.message || "Could not load payments."); setPayments(data.payments); }).catch((reason: Error) => setError(reason.message)); }, []);
  const visible = payments.filter((payment) => `${payment._id} ${payment.invoice?.invoiceNumber} ${payment.freelancer?.name} ${payment.project?.name}`.toLowerCase().includes(search.toLowerCase()) && (filter === "All" || payment.status === filter));
  const completed = payments.filter((payment) => payment.status === "Completed").reduce((sum, payment) => sum + payment.amount, 0);
  const pending = payments.filter((payment) => payment.status === "Pending").reduce((sum, payment) => sum + payment.amount, 0);
  return <main className="min-h-screen bg-slate-950 text-white"><header className="border-b border-slate-800 bg-slate-900 px-6 py-4 flex justify-between"><Link href="/client/dashboard" className="text-xl font-bold">Freelancer<span className="text-blue-500">Portal</span></Link><Link href="/client/dashboard" className="text-slate-400">Dashboard</Link></header><section className="max-w-7xl mx-auto p-6 md:p-8"><h1 className="text-3xl font-bold">Payment History</h1><p className="text-slate-400 mt-2">Payments recorded against invoices linked to your account.</p>{error && <p role="alert" className="mt-4 text-red-400">{error}</p>}<div className="grid md:grid-cols-3 gap-4 my-7">{[["Transactions", payments.length], ["Completed", `₹${completed.toLocaleString("en-IN")}`], ["Pending", `₹${pending.toLocaleString("en-IN")}`]].map(([label, value]) => <div key={String(label)} className="bg-slate-900 border border-slate-800 rounded-xl p-5"><p className="text-slate-400">{label}</p><p className="text-2xl font-bold mt-2">{value}</p></div>)}</div><div className="flex flex-col md:flex-row gap-3 mb-5"><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search payment, invoice, project" className="flex-1 bg-slate-900 border border-slate-800 rounded-lg px-4 py-3"/><select value={filter} onChange={(event) => setFilter(event.target.value)} className="bg-slate-900 border border-slate-800 rounded-lg px-4 py-3"><option>All</option><option>Completed</option><option>Pending</option></select></div><div className="overflow-x-auto bg-slate-900 border border-slate-800 rounded-xl"><table className="w-full"><thead><tr>{["Payment", "Invoice", "Freelancer", "Project", "Amount", "Date", "Method", "Status"].map((heading) => <th key={heading} className="text-left px-4 py-4 text-sm text-slate-400">{heading}</th>)}</tr></thead><tbody>{visible.map((payment) => <tr key={payment._id} className="border-t border-slate-800"><td className="px-4 py-4">{payment._id.slice(-8).toUpperCase()}</td><td className="px-4 py-4">{payment.invoice?.invoiceNumber}</td><td className="px-4 py-4">{payment.freelancer?.name}</td><td className="px-4 py-4">{payment.project?.name}</td><td className="px-4 py-4">₹{payment.amount.toLocaleString("en-IN")}</td><td className="px-4 py-4">{new Date(payment.paymentDate).toLocaleDateString("en-IN")}</td><td className="px-4 py-4">{payment.paymentMethod}</td><td className="px-4 py-4">{payment.status}</td></tr>)}</tbody></table>{visible.length === 0 && <p className="p-8 text-center text-slate-400">No payment records found.</p>}</div><p className="text-slate-500 text-sm mt-4">Payment history is a record of payments. No online payment gateway is configured.</p></section></main>;
}
